import Vue from 'vue';
import HaiButton from '@/components/singhai-ui/button/index';
import HaiInput from '@/components/singhai-ui/input/index';
import HaiSelect from '@/components/singhai-ui/select/index';
import HaiLoading from '@/components/singhai-ui/loading/index';
import HaiSwitch from '@/components/singhai-ui/switch/index';
Vue.use(HaiButton);
Vue.use(HaiInput);
Vue.use(HaiSelect);
Vue.use(HaiLoading);
Vue.use(HaiSwitch);
