declare module 'video.js';
declare module 'wangeditor';
declare module 'qs';
declare module '@/assets/js/utils/secret';
declare module 'vconsole';
declare module 'lodash';
declare module 'nprogress';
declare module 'vue-qr';
declare module 'vue-clipboard2';
